server:
  port: 1113
spring:
  application:
    name: account-service
#zipkin 地址
  zipkin:
    base-url: http://localhost:1117
    enabled: true
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  cloud:
    config:
      name: account-service
      profile: dev
      label: master
      discovery:
        enabled: true               # 开启Config服务发现支持
        service-id: config-server

management:
  security:
    enabled: false  #利用Actuator暴露的refresh接口来实现配置的动态更新,客户端management配置,post请求时不会报HTTP(401)未授权

