server:
  port: 1113

spring:
  application:
    name: account-service

  zipkin:
    base-url: http://localhost:1117 #zipkin 地址
    enabled: true

  sleuth:
    enabled: true
    sampler:
      percentage: 1 # 追踪消息的百分比,1 是所有

  cloud:
    config:
      name: account-service
      profile: dev
      label: master
      discovery:
        enabled: true               # 开启Config服务发现支持
        service-id: config-server

    bus:
      trace:
        enabled: true #开启消息跟踪

  rabbitmq:
    host: 127.0.0.1
    port: 5672

#利用Actuator暴露的refresh接口来实现配置的动态更新,客户端management配置,post请求时不会报HTTP(401)未授权
management:
  security:
    enabled: false

