server:
  port: 1115
spring:
  application:
    name: assets-service
  #zipkin 地址
  zipkin:
    enabled: true
    base-url: http://localhost:1117
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
  cloud:
    config:
      discovery:
        enabled: true
management:
  security:
    enabled: false  #利用Actuator暴露的refresh接口来实现配置的动态更新,客户端management配置,post请求时不会报HTTP(401)未授权

logging:
  level:
    root: info





