spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gitchenhe/config  #git仓库地址
          search-paths: springcloudtest #git仓库下的相对路径,可以配置多个,用逗号分隔
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672

server:
  port: 1111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka

logging:
  level:
    root: info

management:
  security:
    enabled: false  #利用Actuator暴露的refresh接口来实现配置的动态更新,客户端management配置,post请求时不会报HTTP(401)未授权





